In [1]:
#setup
import pandas as pd
import numpy as np
import os

In [3]:
url='https://github.com/USCOVIDpolicy/COVID-19-US-State-Policy-Database/blob/master/COVID-19%20US%20state%20policy%20database%203_30_2022.xlsx?raw=true'
df=pd.read_excel(url, sheet_name='State policy changes ')
path="C:/Users/rivera30/OneDrive - NYU Langone Health/EvictionMoratoria_OD/"

In [4]:
df.head()

,STATE,POSTCODE,FIPS,STEMERG,STEMERGEND,STEMERG2,CLSCHOOL,CLDAYCR,OPNCLDCR,CLNURSHM,...,MINWAGEMAR2019,MINWAGEJUL2019,MINWAGEOCT2019,MINWAGEJAN2020,MINWAGEJUL2020,MINWAGESEP2020,MINWAGEOCT2020,TIPMINWAGE2020,MINWAGE2021,SMALLBUSMINWAGE
0,State,State Abbreviation,FIPS Code,State of emergency issued,State of emergency lifted,State of emergency reinstated,Date closed K-12 public schools,Closed day cares,Reopen day cares,Date banned visitors to nursing homes,...,Mar 29 2019 Minimum Wage,Jul 1 2019 Minimum Wage,Oct 1 2019 Minimum Wage,Jan 1 2020 Minimum Wage,Jul 1 2020 Minimum Wage,Sep 1 2020 Minimum Wage,Oct 1 2020 Minimum Wage,2020 Minimum Wage for Tipped Workers,2021 Minimum Wage,Different Minimum Wage for Smaller Businesses
1,category,NaN,NaN,state_of_emergency,state_of_emergency,state_of_emergency,physical_distance_closure,physical_distance_closure,Reopening,physical_distance_closure,...,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage
2,type,note,note,start,end,start,start,start,end,start,...,quantity,quantity,quantity,quantity,quantity,quantity,quantity,quantity,quantity,attribute
3,unit,text,attribute,date,date,date,date,date,date,date,...,dollars,dollars,dollars,dollars,dollars,dollars,dollars,dollars,dollars,flag
4,Alabama,AL,1,2020-03-13 00:00:00,2021-07-06 00:00:00,2021-08-13 00:00:00,2020-03-20 00:00:00,2020-03-20 00:00:00,2020-05-23 00:00:00,2020-03-19 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0

In [5]:
filter = ((df == 'state_of_emergency')  | (df == 'physical_distance_closure')  | (df == 'SUD_policies')  | (df == 'SUD_policies')  
          | (df == 'housing')  | (df == 'minimum_wage') | (df == 'State')| (df == 'State Abbreviation')| (df == 'FIPS Code')) .any()

sub_df = df.loc[: , filter]

In [6]:
sub_df

,STATE,POSTCODE,FIPS,STEMERG,STEMERGEND,STEMERG2,CLSCHOOL,CLDAYCR,CLNURSHM,CLBSNS,...,MINWAGEMAR2019,MINWAGEJUL2019,MINWAGEOCT2019,MINWAGEJAN2020,MINWAGEJUL2020,MINWAGESEP2020,MINWAGEOCT2020,TIPMINWAGE2020,MINWAGE2021,SMALLBUSMINWAGE
0,State,State Abbreviation,FIPS Code,State of emergency issued,State of emergency lifted,State of emergency reinstated,Date closed K-12 public schools,Closed day cares,Date banned visitors to nursing homes,Closed other non-essential businesses,...,Mar 29 2019 Minimum Wage,Jul 1 2019 Minimum Wage,Oct 1 2019 Minimum Wage,Jan 1 2020 Minimum Wage,Jul 1 2020 Minimum Wage,Sep 1 2020 Minimum Wage,Oct 1 2020 Minimum Wage,2020 Minimum Wage for Tipped Workers,2021 Minimum Wage,Different Minimum Wage for Smaller Businesses
1,category,NaN,NaN,state_of_emergency,state_of_emergency,state_of_emergency,physical_distance_closure,physical_distance_closure,physical_distance_closure,physical_distance_closure,...,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage,minimum_wage
2,type,note,note,start,end,start,start,start,start,start,...,quantity,quantity,quantity,quantity,quantity,quantity,quantity,quantity,quantity,attribute
3,unit,text,attribute,date,date,date,date,date,date,date,...,dollars,dollars,dollars,dollars,dollars,dollars,dollars,dollars,dollars,flag
4,Alabama,AL,1,2020-03-13 00:00:00,2021-07-06 00:00:00,2021-08-13 00:00:00,2020-03-20 00:00:00,2020-03-20 00:00:00,2020-03-19 00:00:00,2020-03-28 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
5,Alaska,AK,2,2020-03-11 00:00:00,2021-04-30 00:00:00,0,2020-03-16 00:00:00,0,0,2020-03-24 00:00:00,...,9.89,9.89,9.89,10.19,10.19,10.19,10.19,10.19,10.34,0
6,Arizona,AZ,4,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-31 00:00:00,...,11,11,11,12,12,12,12,9,12.15,0
7,Arkansas,AR,5,2020-03-11 00:00:00,2021-05-30 00:00:00,2021-07-29 00:00:00,2020-03-17 00:00:00,0,2020-03-13 00:00:00,2020-04-06 00:00:00,...,9.25,9.25,9.25,10,10,10,10,2.63,11,1
8,California,CA,6,2020-03-04 00:00:00,0,0,2020-03-23 00:00:00,0,0,2020-03-19 00:00:00,...,12,12,12,13,13,13,13,13,14,1
9,Colorado,CO,8,2020-03-11 00:00:00,2021-07-08 00:00:00,0,2020-03-23 00:00:00,0,2020-03-12 00:00:00,2020-03-19 00:00:00,...,11.1,11.1,11.1,12,12,12,12,8.98,12.32,1
10,Connecticut,CT,9,2020-03-10 00:00:00,0,0,2020-03-17 00:00:00,0,2020-03-09 00:00:00,2020-03-23 00:00:00,...,10.1,10.1,11,11,11,12,12,6.38,12,0
11,Delaware,DE,10,2020-03-13 00:00:00,2021-07-12 00:00:00,0,2020-03-16 00:00:00,2020-04-06 00:00:00,0,2020-03-24 00:00:00,...,8.75,8.75,9.25,9.25,9.25,9.25,9.25,2.23,9.25,0
12,District of Columbia,DC,11,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-25 00:00:00,...,13.25,14,14,14,15,15,15,5,15,0
13,Florida,FL,12,2020-03-09 00:00:00,2021-06-26 00:00:00,0,2020-03-17 00:00:00,0,2020-03-15 00:00:00,2020-04-03 00:00:00,...,8.46,8.46,8.46,8.56,8.56,8.56,8.56,5.54,8.65,0
14,Georgia,GA,13,2020-03-14 00:00:00,2021-07-01 00:00:00,0,2020-03-18 00:00:00,0,2020-04-03 00:00:00,2020-04-03 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
15,Hawaii,HI,15,2020-03-04 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-17 00:00:00,2020-03-25 00:00:00,...,10.1,10.1,10.1,10.1,10.1,10.1,10.1,9.35,10.1,0
16,Idaho,ID,16,2020-03-13 00:00:00,0,0,2020-03-24 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,3.35,7.25,0
17,Illinois,IL,17,2020-03-09 00:00:00,0,0,2020-03-17 00:00:00,2020-03-23 00:00:00,0,2020-03-21 00:00:00,...,8.25,8.25,8.25,9.25,10,10,10,6,11,1
18,Indiana,IN,18,2020-03-06 00:00:00,0,0,2020-03-20 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
19,Iowa,IA,19,2020-03-09 00:00:00,0,0,2020-04-02 00:00:00,0,0,2020-03-26 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,4.35,7.25,0
20,Kansas,KS,20,2020-03-12 00:00:00,2021-06-15 00:00:00,0,2020-03-18 00:00:00,0,0,2020-03-30 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
21,Kentucky,KY,21,2020-03-06 00:00:00,0,0,2020-03-17 00:00:00,2020-03-23 00:00:00,0,2020-03-26 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
22,Louisiana,LA,22,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-12 00:00:00,2020-03-23 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
23,Maine,ME,23,2020-03-15 00:00:00,2021-06-30 00:00:00,0,2020-04-02 00:00:00,0,0,2020-03-25 00:00:00,...,11,11,11,12,12,12,12,6,12.15,0
24,Maryland,MD,24,2020-03-05 00:00:00,2021-07-01 00:00:00,0,2020-03-16 00:00:00,2020-03-30 00:00:00,2020-04-05 00:00:00,2020-03-23 00:00:00,...,10.1,10.1,10.1,11,11,11,11,3.63,11.75,0
25,Massachusetts,MA,25,2020-03-10 00:00:00,2021-06-15 00:00:00,0,2020-03-17 00:00:00,2020-03-23 00:00:00,2020-03-16 00:00:00,2020-03-24 00:00:00,...,12,12,12,12.75,12.75,12.75,12.75,4.95,13.5,0
26,Michigan,MI,26,2020-03-10 00:00:00,2020-10-02 00:00:00,0,2020-03-16 00:00:00,2020-03-24 00:00:00,2020-03-14 00:00:00,2020-03-24 00:00:00,...,9.45,9.45,9.45,9.65,9.65,9.65,9.65,3.67,9.65,1
27,Minnesota,MN,27,2020-03-13 00:00:00,2021-07-01 00:00:00,0,2020-03-18 00:00:00,0,0,2020-03-28 00:00:00,...,9.86,9.86,9.86,10,10,10,10,8.15,10.08,1
28,Mississippi,MS,28,2020-03-14 00:00:00,0,0,2020-03-20 00:00:00,0,2020-03-24 00:00:00,2020-04-03 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
29,Missouri,MO,29,2020-03-13 00:00:00,0,0,2020-03-23 00:00:00,0,2020-03-23 00:00:00,2020-04-03 00:00:00,...,8.6,8.6,8.6,9.45,9.45,9.45,9.45,4.73,10.3,1
30,Montana,MT,30,2020-03-12 00:00:00,2021-06-30 00:00:00,0,2020-03-16 00:00:00,0,2020-03-15 00:00:00,2020-03-28 00:00:00,...,8.5,8.5,8.5,8.65,8.65,8.65,8.65,4,8.75,1
31,Nebraska,NE,31,2020-03-13 00:00:00,0,0,2020-04-03 00:00:00,0,0,2020-04-09 00:00:00,...,9,9,9,9,9,9,9,2.13,9,1
32,Nevada,NV,32,2020-03-12 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-21 00:00:00,...,8.25,8.25,8.25,8.25,9,9,9,8,9,1
33,New Hampshire,NH,33,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-16 00:00:00,2020-03-28 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,3.26,7.25,0
34,New Jersey,NJ,34,2020-03-09 00:00:00,2021-06-04 00:00:00,0,2020-03-18 00:00:00,2020-03-18 00:00:00,2020-06-19 00:00:00,2020-03-21 00:00:00,...,8.85,10,10,11,11,11,11,3.13,12,0
35,New Mexico,NM,35,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-13 00:00:00,2020-03-24 00:00:00,...,7.5,7.5,7.5,9,9,9,9,2.35,10.5,0
36,New York,NY,36,2020-03-07 00:00:00,2021-06-25 00:00:00,0,2020-03-18 00:00:00,0,2020-03-13 00:00:00,2020-03-22 00:00:00,...,11.1,11.1,11.1,11.8,11.8,11.8,11.8,7.85,12.5,0
37,North Carolina,NC,37,2020-03-10 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-25 00:00:00,2020-03-30 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
38,North Dakota,ND,38,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,2020-04-06 00:00:00,2020-03-20 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,4.86,7.25,0
39,Ohio,OH,39,2020-03-09 00:00:00,2021-06-18 00:00:00,0,2020-03-17 00:00:00,2020-03-26 00:00:00,2020-03-11 00:00:00,2020-03-24 00:00:00,...,8.55,8.55,8.55,8.7,8.7,8.7,8.7,4.35,8.8,1
40,Oklahoma,OK,40,2020-03-15 00:00:00,2021-05-04 00:00:00,0,2020-03-17 00:00:00,0,2020-03-24 00:00:00,2020-04-01 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
41,Oregon,OR,41,2020-03-08 00:00:00,0,0,2020-03-16 00:00:00,2020-03-25 00:00:00,2020-03-16 00:00:00,2020-03-23 00:00:00,...,10.75,11.25,11.25,11.25,12,12,12,11.5,12,0
42,Pennsylvania,PA,42,2020-03-06 00:00:00,2021-06-10 00:00:00,0,2020-03-16 00:00:00,2020-03-17 00:00:00,2020-03-17 00:00:00,2020-03-21 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.83,7.25,0
43,Rhode Island,RI,44,2020-03-09 00:00:00,0,0,0,2020-03-16 00:00:00,2020-03-13 00:00:00,2020-03-30 00:00:00,...,10.5,10.5,10.5,10.5,10.5,10.5,11.5,3.89,11.5,0
44,South Carolina,SC,45,2020-03-13 00:00:00,2021-06-07 00:00:00,0,2020-03-16 00:00:00,0,2020-03-15 00:00:00,2020-04-01 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
45,South Dakota,SD,46,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,0,0,...,9.1,9.1,9.1,9.3,9.3,9.3,9.3,4.65,9.45,0
46,Tennessee,TN,47,2020-03-12 00:00:00,0,0,2020-03-20 00:00:00,0,2020-03-23 00:00:00,2020-04-01 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
47,Texas,TX,48,2020-03-13 00:00:00,0,0,2020-03-21 00:00:00,0,2020-03-21 00:00:00,2020-04-02 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
48,Utah,UT,49,2020-03-06 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-27 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
49,Vermont,VT,50,2020-03-13 00:00:00,2021-06-16 00:00:00,0,2020-03-18 00:00:00,2020-03-18 00:00:00,2020-03-13 00:00:00,2020-03-25 00:00:00,...,10.78,10.78,10.78,10.96,10.96,10.96,10.96,5.46,11.75,1
50,Virginia,VA,51,2020-03-12 00:00:00,2021-07-01 00:00:00,0,2020-03-16 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
51,Washington,WA,53,2020-02-29 00:00:00,0,0,2020-03-17 00:00:00,0,2020-03-16 00:00:00,2020-03-25 00:00:00,...,12,12,12,13.5,13.5,13.5,13.5,13.5,13.69,0
52,West Virginia,WV,54,2020-03-16 00:00:00,0,0,2020-03-16 00:00:00,2020-03-26 00:00:00,2020-08-13 00:00:00,2020-03-24 00:00:00,...,8.75,8.75,8.75,8.75,8.75,8.75,8.75,2.62,8.75,1
53,Wisconsin,WI,55,2020-03-12 00:00:00,0,0,2020-03-18 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.33,7.25,0
54,Wyoming,WY,56,2020-03-13 00:00:00,0,0,2020-03-19 00:00:00,2020-03-19 00:00:00,0,2020-03-19 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0

In [7]:
#remove attribute rows
sub_df = sub_df.drop(labels=[0,1,2,3], axis=0)
sub_df

,STATE,POSTCODE,FIPS,STEMERG,STEMERGEND,STEMERG2,CLSCHOOL,CLDAYCR,CLNURSHM,CLBSNS,...,MINWAGEMAR2019,MINWAGEJUL2019,MINWAGEOCT2019,MINWAGEJAN2020,MINWAGEJUL2020,MINWAGESEP2020,MINWAGEOCT2020,TIPMINWAGE2020,MINWAGE2021,SMALLBUSMINWAGE
4,Alabama,AL,1,2020-03-13 00:00:00,2021-07-06 00:00:00,2021-08-13 00:00:00,2020-03-20 00:00:00,2020-03-20 00:00:00,2020-03-19 00:00:00,2020-03-28 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
5,Alaska,AK,2,2020-03-11 00:00:00,2021-04-30 00:00:00,0,2020-03-16 00:00:00,0,0,2020-03-24 00:00:00,...,9.89,9.89,9.89,10.19,10.19,10.19,10.19,10.19,10.34,0
6,Arizona,AZ,4,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-31 00:00:00,...,11,11,11,12,12,12,12,9,12.15,0
7,Arkansas,AR,5,2020-03-11 00:00:00,2021-05-30 00:00:00,2021-07-29 00:00:00,2020-03-17 00:00:00,0,2020-03-13 00:00:00,2020-04-06 00:00:00,...,9.25,9.25,9.25,10,10,10,10,2.63,11,1
8,California,CA,6,2020-03-04 00:00:00,0,0,2020-03-23 00:00:00,0,0,2020-03-19 00:00:00,...,12,12,12,13,13,13,13,13,14,1
9,Colorado,CO,8,2020-03-11 00:00:00,2021-07-08 00:00:00,0,2020-03-23 00:00:00,0,2020-03-12 00:00:00,2020-03-19 00:00:00,...,11.1,11.1,11.1,12,12,12,12,8.98,12.32,1
10,Connecticut,CT,9,2020-03-10 00:00:00,0,0,2020-03-17 00:00:00,0,2020-03-09 00:00:00,2020-03-23 00:00:00,...,10.1,10.1,11,11,11,12,12,6.38,12,0
11,Delaware,DE,10,2020-03-13 00:00:00,2021-07-12 00:00:00,0,2020-03-16 00:00:00,2020-04-06 00:00:00,0,2020-03-24 00:00:00,...,8.75,8.75,9.25,9.25,9.25,9.25,9.25,2.23,9.25,0
12,District of Columbia,DC,11,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-25 00:00:00,...,13.25,14,14,14,15,15,15,5,15,0
13,Florida,FL,12,2020-03-09 00:00:00,2021-06-26 00:00:00,0,2020-03-17 00:00:00,0,2020-03-15 00:00:00,2020-04-03 00:00:00,...,8.46,8.46,8.46,8.56,8.56,8.56,8.56,5.54,8.65,0
14,Georgia,GA,13,2020-03-14 00:00:00,2021-07-01 00:00:00,0,2020-03-18 00:00:00,0,2020-04-03 00:00:00,2020-04-03 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
15,Hawaii,HI,15,2020-03-04 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-17 00:00:00,2020-03-25 00:00:00,...,10.1,10.1,10.1,10.1,10.1,10.1,10.1,9.35,10.1,0
16,Idaho,ID,16,2020-03-13 00:00:00,0,0,2020-03-24 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,3.35,7.25,0
17,Illinois,IL,17,2020-03-09 00:00:00,0,0,2020-03-17 00:00:00,2020-03-23 00:00:00,0,2020-03-21 00:00:00,...,8.25,8.25,8.25,9.25,10,10,10,6,11,1
18,Indiana,IN,18,2020-03-06 00:00:00,0,0,2020-03-20 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
19,Iowa,IA,19,2020-03-09 00:00:00,0,0,2020-04-02 00:00:00,0,0,2020-03-26 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,4.35,7.25,0
20,Kansas,KS,20,2020-03-12 00:00:00,2021-06-15 00:00:00,0,2020-03-18 00:00:00,0,0,2020-03-30 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
21,Kentucky,KY,21,2020-03-06 00:00:00,0,0,2020-03-17 00:00:00,2020-03-23 00:00:00,0,2020-03-26 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
22,Louisiana,LA,22,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-12 00:00:00,2020-03-23 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
23,Maine,ME,23,2020-03-15 00:00:00,2021-06-30 00:00:00,0,2020-04-02 00:00:00,0,0,2020-03-25 00:00:00,...,11,11,11,12,12,12,12,6,12.15,0
24,Maryland,MD,24,2020-03-05 00:00:00,2021-07-01 00:00:00,0,2020-03-16 00:00:00,2020-03-30 00:00:00,2020-04-05 00:00:00,2020-03-23 00:00:00,...,10.1,10.1,10.1,11,11,11,11,3.63,11.75,0
25,Massachusetts,MA,25,2020-03-10 00:00:00,2021-06-15 00:00:00,0,2020-03-17 00:00:00,2020-03-23 00:00:00,2020-03-16 00:00:00,2020-03-24 00:00:00,...,12,12,12,12.75,12.75,12.75,12.75,4.95,13.5,0
26,Michigan,MI,26,2020-03-10 00:00:00,2020-10-02 00:00:00,0,2020-03-16 00:00:00,2020-03-24 00:00:00,2020-03-14 00:00:00,2020-03-24 00:00:00,...,9.45,9.45,9.45,9.65,9.65,9.65,9.65,3.67,9.65,1
27,Minnesota,MN,27,2020-03-13 00:00:00,2021-07-01 00:00:00,0,2020-03-18 00:00:00,0,0,2020-03-28 00:00:00,...,9.86,9.86,9.86,10,10,10,10,8.15,10.08,1
28,Mississippi,MS,28,2020-03-14 00:00:00,0,0,2020-03-20 00:00:00,0,2020-03-24 00:00:00,2020-04-03 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
29,Missouri,MO,29,2020-03-13 00:00:00,0,0,2020-03-23 00:00:00,0,2020-03-23 00:00:00,2020-04-03 00:00:00,...,8.6,8.6,8.6,9.45,9.45,9.45,9.45,4.73,10.3,1
30,Montana,MT,30,2020-03-12 00:00:00,2021-06-30 00:00:00,0,2020-03-16 00:00:00,0,2020-03-15 00:00:00,2020-03-28 00:00:00,...,8.5,8.5,8.5,8.65,8.65,8.65,8.65,4,8.75,1
31,Nebraska,NE,31,2020-03-13 00:00:00,0,0,2020-04-03 00:00:00,0,0,2020-04-09 00:00:00,...,9,9,9,9,9,9,9,2.13,9,1
32,Nevada,NV,32,2020-03-12 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-21 00:00:00,...,8.25,8.25,8.25,8.25,9,9,9,8,9,1
33,New Hampshire,NH,33,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-16 00:00:00,2020-03-28 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,3.26,7.25,0
34,New Jersey,NJ,34,2020-03-09 00:00:00,2021-06-04 00:00:00,0,2020-03-18 00:00:00,2020-03-18 00:00:00,2020-06-19 00:00:00,2020-03-21 00:00:00,...,8.85,10,10,11,11,11,11,3.13,12,0
35,New Mexico,NM,35,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-13 00:00:00,2020-03-24 00:00:00,...,7.5,7.5,7.5,9,9,9,9,2.35,10.5,0
36,New York,NY,36,2020-03-07 00:00:00,2021-06-25 00:00:00,0,2020-03-18 00:00:00,0,2020-03-13 00:00:00,2020-03-22 00:00:00,...,11.1,11.1,11.1,11.8,11.8,11.8,11.8,7.85,12.5,0
37,North Carolina,NC,37,2020-03-10 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-25 00:00:00,2020-03-30 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
38,North Dakota,ND,38,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,2020-04-06 00:00:00,2020-03-20 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,4.86,7.25,0
39,Ohio,OH,39,2020-03-09 00:00:00,2021-06-18 00:00:00,0,2020-03-17 00:00:00,2020-03-26 00:00:00,2020-03-11 00:00:00,2020-03-24 00:00:00,...,8.55,8.55,8.55,8.7,8.7,8.7,8.7,4.35,8.8,1
40,Oklahoma,OK,40,2020-03-15 00:00:00,2021-05-04 00:00:00,0,2020-03-17 00:00:00,0,2020-03-24 00:00:00,2020-04-01 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
41,Oregon,OR,41,2020-03-08 00:00:00,0,0,2020-03-16 00:00:00,2020-03-25 00:00:00,2020-03-16 00:00:00,2020-03-23 00:00:00,...,10.75,11.25,11.25,11.25,12,12,12,11.5,12,0
42,Pennsylvania,PA,42,2020-03-06 00:00:00,2021-06-10 00:00:00,0,2020-03-16 00:00:00,2020-03-17 00:00:00,2020-03-17 00:00:00,2020-03-21 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.83,7.25,0
43,Rhode Island,RI,44,2020-03-09 00:00:00,0,0,0,2020-03-16 00:00:00,2020-03-13 00:00:00,2020-03-30 00:00:00,...,10.5,10.5,10.5,10.5,10.5,10.5,11.5,3.89,11.5,0
44,South Carolina,SC,45,2020-03-13 00:00:00,2021-06-07 00:00:00,0,2020-03-16 00:00:00,0,2020-03-15 00:00:00,2020-04-01 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
45,South Dakota,SD,46,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,0,0,...,9.1,9.1,9.1,9.3,9.3,9.3,9.3,4.65,9.45,0
46,Tennessee,TN,47,2020-03-12 00:00:00,0,0,2020-03-20 00:00:00,0,2020-03-23 00:00:00,2020-04-01 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
47,Texas,TX,48,2020-03-13 00:00:00,0,0,2020-03-21 00:00:00,0,2020-03-21 00:00:00,2020-04-02 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
48,Utah,UT,49,2020-03-06 00:00:00,0,0,2020-03-16 00:00:00,0,0,2020-03-27 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
49,Vermont,VT,50,2020-03-13 00:00:00,2021-06-16 00:00:00,0,2020-03-18 00:00:00,2020-03-18 00:00:00,2020-03-13 00:00:00,2020-03-25 00:00:00,...,10.78,10.78,10.78,10.96,10.96,10.96,10.96,5.46,11.75,1
50,Virginia,VA,51,2020-03-12 00:00:00,2021-07-01 00:00:00,0,2020-03-16 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
51,Washington,WA,53,2020-02-29 00:00:00,0,0,2020-03-17 00:00:00,0,2020-03-16 00:00:00,2020-03-25 00:00:00,...,12,12,12,13.5,13.5,13.5,13.5,13.5,13.69,0
52,West Virginia,WV,54,2020-03-16 00:00:00,0,0,2020-03-16 00:00:00,2020-03-26 00:00:00,2020-08-13 00:00:00,2020-03-24 00:00:00,...,8.75,8.75,8.75,8.75,8.75,8.75,8.75,2.62,8.75,1
53,Wisconsin,WI,55,2020-03-12 00:00:00,0,0,2020-03-18 00:00:00,0,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.33,7.25,0
54,Wyoming,WY,56,2020-03-13 00:00:00,0,0,2020-03-19 00:00:00,2020-03-19 00:00:00,0,2020-03-19 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0

In [8]:
sub_df.reset_index()

,index,STATE,POSTCODE,FIPS,STEMERG,STEMERGEND,STEMERG2,CLSCHOOL,CLDAYCR,CLNURSHM,...,MINWAGEMAR2019,MINWAGEJUL2019,MINWAGEOCT2019,MINWAGEJAN2020,MINWAGEJUL2020,MINWAGESEP2020,MINWAGEOCT2020,TIPMINWAGE2020,MINWAGE2021,SMALLBUSMINWAGE
0,4,Alabama,AL,1,2020-03-13 00:00:00,2021-07-06 00:00:00,2021-08-13 00:00:00,2020-03-20 00:00:00,2020-03-20 00:00:00,2020-03-19 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
1,5,Alaska,AK,2,2020-03-11 00:00:00,2021-04-30 00:00:00,0,2020-03-16 00:00:00,0,0,...,9.89,9.89,9.89,10.19,10.19,10.19,10.19,10.19,10.34,0
2,6,Arizona,AZ,4,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,0,...,11,11,11,12,12,12,12,9,12.15,0
3,7,Arkansas,AR,5,2020-03-11 00:00:00,2021-05-30 00:00:00,2021-07-29 00:00:00,2020-03-17 00:00:00,0,2020-03-13 00:00:00,...,9.25,9.25,9.25,10,10,10,10,2.63,11,1
4,8,California,CA,6,2020-03-04 00:00:00,0,0,2020-03-23 00:00:00,0,0,...,12,12,12,13,13,13,13,13,14,1
5,9,Colorado,CO,8,2020-03-11 00:00:00,2021-07-08 00:00:00,0,2020-03-23 00:00:00,0,2020-03-12 00:00:00,...,11.1,11.1,11.1,12,12,12,12,8.98,12.32,1
6,10,Connecticut,CT,9,2020-03-10 00:00:00,0,0,2020-03-17 00:00:00,0,2020-03-09 00:00:00,...,10.1,10.1,11,11,11,12,12,6.38,12,0
7,11,Delaware,DE,10,2020-03-13 00:00:00,2021-07-12 00:00:00,0,2020-03-16 00:00:00,2020-04-06 00:00:00,0,...,8.75,8.75,9.25,9.25,9.25,9.25,9.25,2.23,9.25,0
8,12,District of Columbia,DC,11,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,0,...,13.25,14,14,14,15,15,15,5,15,0
9,13,Florida,FL,12,2020-03-09 00:00:00,2021-06-26 00:00:00,0,2020-03-17 00:00:00,0,2020-03-15 00:00:00,...,8.46,8.46,8.46,8.56,8.56,8.56,8.56,5.54,8.65,0
10,14,Georgia,GA,13,2020-03-14 00:00:00,2021-07-01 00:00:00,0,2020-03-18 00:00:00,0,2020-04-03 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
11,15,Hawaii,HI,15,2020-03-04 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-17 00:00:00,...,10.1,10.1,10.1,10.1,10.1,10.1,10.1,9.35,10.1,0
12,16,Idaho,ID,16,2020-03-13 00:00:00,0,0,2020-03-24 00:00:00,0,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,3.35,7.25,0
13,17,Illinois,IL,17,2020-03-09 00:00:00,0,0,2020-03-17 00:00:00,2020-03-23 00:00:00,0,...,8.25,8.25,8.25,9.25,10,10,10,6,11,1
14,18,Indiana,IN,18,2020-03-06 00:00:00,0,0,2020-03-20 00:00:00,0,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
15,19,Iowa,IA,19,2020-03-09 00:00:00,0,0,2020-04-02 00:00:00,0,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,4.35,7.25,0
16,20,Kansas,KS,20,2020-03-12 00:00:00,2021-06-15 00:00:00,0,2020-03-18 00:00:00,0,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
17,21,Kentucky,KY,21,2020-03-06 00:00:00,0,0,2020-03-17 00:00:00,2020-03-23 00:00:00,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
18,22,Louisiana,LA,22,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-12 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
19,23,Maine,ME,23,2020-03-15 00:00:00,2021-06-30 00:00:00,0,2020-04-02 00:00:00,0,0,...,11,11,11,12,12,12,12,6,12.15,0
20,24,Maryland,MD,24,2020-03-05 00:00:00,2021-07-01 00:00:00,0,2020-03-16 00:00:00,2020-03-30 00:00:00,2020-04-05 00:00:00,...,10.1,10.1,10.1,11,11,11,11,3.63,11.75,0
21,25,Massachusetts,MA,25,2020-03-10 00:00:00,2021-06-15 00:00:00,0,2020-03-17 00:00:00,2020-03-23 00:00:00,2020-03-16 00:00:00,...,12,12,12,12.75,12.75,12.75,12.75,4.95,13.5,0
22,26,Michigan,MI,26,2020-03-10 00:00:00,2020-10-02 00:00:00,0,2020-03-16 00:00:00,2020-03-24 00:00:00,2020-03-14 00:00:00,...,9.45,9.45,9.45,9.65,9.65,9.65,9.65,3.67,9.65,1
23,27,Minnesota,MN,27,2020-03-13 00:00:00,2021-07-01 00:00:00,0,2020-03-18 00:00:00,0,0,...,9.86,9.86,9.86,10,10,10,10,8.15,10.08,1
24,28,Mississippi,MS,28,2020-03-14 00:00:00,0,0,2020-03-20 00:00:00,0,2020-03-24 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
25,29,Missouri,MO,29,2020-03-13 00:00:00,0,0,2020-03-23 00:00:00,0,2020-03-23 00:00:00,...,8.6,8.6,8.6,9.45,9.45,9.45,9.45,4.73,10.3,1
26,30,Montana,MT,30,2020-03-12 00:00:00,2021-06-30 00:00:00,0,2020-03-16 00:00:00,0,2020-03-15 00:00:00,...,8.5,8.5,8.5,8.65,8.65,8.65,8.65,4,8.75,1
27,31,Nebraska,NE,31,2020-03-13 00:00:00,0,0,2020-04-03 00:00:00,0,0,...,9,9,9,9,9,9,9,2.13,9,1
28,32,Nevada,NV,32,2020-03-12 00:00:00,0,0,2020-03-16 00:00:00,0,0,...,8.25,8.25,8.25,8.25,9,9,9,8,9,1
29,33,New Hampshire,NH,33,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-16 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,3.26,7.25,0
30,34,New Jersey,NJ,34,2020-03-09 00:00:00,2021-06-04 00:00:00,0,2020-03-18 00:00:00,2020-03-18 00:00:00,2020-06-19 00:00:00,...,8.85,10,10,11,11,11,11,3.13,12,0
31,35,New Mexico,NM,35,2020-03-11 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-13 00:00:00,...,7.5,7.5,7.5,9,9,9,9,2.35,10.5,0
32,36,New York,NY,36,2020-03-07 00:00:00,2021-06-25 00:00:00,0,2020-03-18 00:00:00,0,2020-03-13 00:00:00,...,11.1,11.1,11.1,11.8,11.8,11.8,11.8,7.85,12.5,0
33,37,North Carolina,NC,37,2020-03-10 00:00:00,0,0,2020-03-16 00:00:00,0,2020-03-25 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
34,38,North Dakota,ND,38,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,2020-04-06 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,4.86,7.25,0
35,39,Ohio,OH,39,2020-03-09 00:00:00,2021-06-18 00:00:00,0,2020-03-17 00:00:00,2020-03-26 00:00:00,2020-03-11 00:00:00,...,8.55,8.55,8.55,8.7,8.7,8.7,8.7,4.35,8.8,1
36,40,Oklahoma,OK,40,2020-03-15 00:00:00,2021-05-04 00:00:00,0,2020-03-17 00:00:00,0,2020-03-24 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
37,41,Oregon,OR,41,2020-03-08 00:00:00,0,0,2020-03-16 00:00:00,2020-03-25 00:00:00,2020-03-16 00:00:00,...,10.75,11.25,11.25,11.25,12,12,12,11.5,12,0
38,42,Pennsylvania,PA,42,2020-03-06 00:00:00,2021-06-10 00:00:00,0,2020-03-16 00:00:00,2020-03-17 00:00:00,2020-03-17 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.83,7.25,0
39,43,Rhode Island,RI,44,2020-03-09 00:00:00,0,0,0,2020-03-16 00:00:00,2020-03-13 00:00:00,...,10.5,10.5,10.5,10.5,10.5,10.5,11.5,3.89,11.5,0
40,44,South Carolina,SC,45,2020-03-13 00:00:00,2021-06-07 00:00:00,0,2020-03-16 00:00:00,0,2020-03-15 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
41,45,South Dakota,SD,46,2020-03-13 00:00:00,0,0,2020-03-16 00:00:00,0,0,...,9.1,9.1,9.1,9.3,9.3,9.3,9.3,4.65,9.45,0
42,46,Tennessee,TN,47,2020-03-12 00:00:00,0,0,2020-03-20 00:00:00,0,2020-03-23 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
43,47,Texas,TX,48,2020-03-13 00:00:00,0,0,2020-03-21 00:00:00,0,2020-03-21 00:00:00,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
44,48,Utah,UT,49,2020-03-06 00:00:00,0,0,2020-03-16 00:00:00,0,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0
45,49,Vermont,VT,50,2020-03-13 00:00:00,2021-06-16 00:00:00,0,2020-03-18 00:00:00,2020-03-18 00:00:00,2020-03-13 00:00:00,...,10.78,10.78,10.78,10.96,10.96,10.96,10.96,5.46,11.75,1
46,50,Virginia,VA,51,2020-03-12 00:00:00,2021-07-01 00:00:00,0,2020-03-16 00:00:00,0,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,1
47,51,Washington,WA,53,2020-02-29 00:00:00,0,0,2020-03-17 00:00:00,0,2020-03-16 00:00:00,...,12,12,12,13.5,13.5,13.5,13.5,13.5,13.69,0
48,52,West Virginia,WV,54,2020-03-16 00:00:00,0,0,2020-03-16 00:00:00,2020-03-26 00:00:00,2020-08-13 00:00:00,...,8.75,8.75,8.75,8.75,8.75,8.75,8.75,2.62,8.75,1
49,53,Wisconsin,WI,55,2020-03-12 00:00:00,0,0,2020-03-18 00:00:00,0,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.33,7.25,0
50,54,Wyoming,WY,56,2020-03-13 00:00:00,0,0,2020-03-19 00:00:00,2020-03-19 00:00:00,0,...,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0

In [9]:
#Create month year

In [10]:
sub_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51 entries, 4 to 54
Data columns (total 68 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   STATE                51 non-null     object
 1   POSTCODE             51 non-null     object
 2   FIPS                 51 non-null     object
 3   STEMERG              51 non-null     object
 4   STEMERGEND           51 non-null     object
 5   STEMERG2             51 non-null     object
 6   CLSCHOOL             51 non-null     object
 7   CLDAYCR              51 non-null     object
 8   CLNURSHM             51 non-null     object
 9   CLBSNS               51 non-null     object
 10  CURFEW               51 non-null     object
 11  EMSTART              51 non-null     object
 12  EMEND                51 non-null     object
 13  EMSTART2             51 non-null     object
 14  EMEND2               51 non-null     object
 15  EMSTART3             51 non-null     object
 16  EMEND3               51 non-null     object
 17  EMNOW                51 non-null     object
 18  INITIATIONBANSTART   51 non-null     object
 19  INITIATIONBANEND     51 non-null     object
 20  INITIATIONBANSTART2  51 non-null     object
 21  INITIATIONBANEND2    51 non-null     object
 22  HEARINGBANSTART      51 non-null     object
 23  HEARINGBANEND        51 non-null     object
 24  HEARINGBANSTART2     51 non-null     object
 25  HEARINGBANEND2       51 non-null     object
 26  ENFORCEBANSTART      51 non-null     object
 27  ENFORCEBANEND        51 non-null     object
 28  ENFORCEBANSTART2     51 non-null     object
 29  ENFORCEBANEND2       51 non-null     object
 30  C19START             51 non-null     object
 31  C19END               51 non-null     object
 32  C19START2            51 non-null     object
 33  C19END2              51 non-null     object
 34  PAYSTART             51 non-null     object
 35  PAYEND               51 non-null     object
 36  PAYSTART2            51 non-null     object
 37  PAYEND2              51 non-null     object
 38  CARESSTART           51 non-null     object
 39  CARESEND             51 non-null     object
 40  CDCSTART             51 non-null     object
 41  CDCEND               51 non-null     object
 42  LATESTART            51 non-null     object
 43  LATEEND              51 non-null     object
 44  LATESTART2           51 non-null     object
 45  LATEEND2             51 non-null     object
 46  SMSTART              51 non-null     object
 47  SMEND                51 non-null     object
 48  SMSTART2             51 non-null     object
 49  URSTART              51 non-null     object
 50  UREND                51 non-null     object
 51  TLHlBUPR             51 non-null     object
 52  EXTOPFL              51 non-null     object
 53  HMDLVOP              51 non-null     object
 54  TLHLCL24             51 non-null     object
 55  EXCEMORP             51 non-null     object
 56  WVDEAREQ             51 non-null     object
 57  MINWAGEJAN2019       51 non-null     object
 58  MINWAGEMAR2019       51 non-null     object
 59  MINWAGEJUL2019       51 non-null     object
 60  MINWAGEOCT2019       51 non-null     object
 61  MINWAGEJAN2020       51 non-null     object
 62  MINWAGEJUL2020       51 non-null     object
 63  MINWAGESEP2020       51 non-null     object
 64  MINWAGEOCT2020       51 non-null     object
 65  TIPMINWAGE2020       51 non-null     object
 66  MINWAGE2021          51 non-null     object
 67  SMALLBUSMINWAGE      51 non-null     object
dtypes: object(68)
memory usage: 27.5+ KB

In [11]:
sub_df.to_csv(os.path.join(path, "data", "2_intermediate", "cusp.csv"))