In [1]:
#setup
import pandas as pd
import numpy as np
import os
import requests
import json
import prettytable
import io
import csv
import time
import glob

Running the code requires, this script to be saved under folder code, and a folder structure as follows:

	EvictionMoratoria_OD/
	|-	code      # Where the scripts are stored
	|-	data      # Data files organized as follows
	|	|-	1_raw				# All files as obtained from the source
		 |-	2_intermediate 		# All intermediate dataset

In [2]:
#list of all county FIPS codes:
geofips = pd.read_csv('..\\data\\2_intermediate\\geofips.csv')
geofips

      geofips
0        1001
1        1003
2        1005
3        1007
4        1009
...       ...
3137    56037
3138    56039
3139    56041
3140    56043
3141    56045

[3142 rows x 1 columns]

In [3]:
series_ids = ["LAUCN" + str(x).zfill(5) + '0000000003' for x in geofips['geofips']]

In [4]:
series_ids

['LAUCN010010000000003',
 'LAUCN010030000000003',
 'LAUCN010050000000003',
 'LAUCN010070000000003',
 'LAUCN010090000000003',
 'LAUCN010110000000003',
 'LAUCN010130000000003',
 'LAUCN010150000000003',
 'LAUCN010170000000003',
 'LAUCN010190000000003',
 'LAUCN010210000000003',
 'LAUCN010230000000003',
 'LAUCN010250000000003',
 'LAUCN010270000000003',
 'LAUCN010290000000003',
 'LAUCN010310000000003',
 'LAUCN010330000000003',
 'LAUCN010350000000003',
 'LAUCN010370000000003',
 'LAUCN010390000000003',
 'LAUCN010410000000003',
 'LAUCN010430000000003',
 'LAUCN010450000000003',
 'LAUCN010470000000003',
 'LAUCN010490000000003',
 'LAUCN010510000000003',
 'LAUCN010530000000003',
 'LAUCN010550000000003',
 'LAUCN010570000000003',
 'LAUCN010590000000003',
 'LAUCN010610000000003',
 'LAUCN010630000000003',
 'LAUCN010650000000003',
 'LAUCN010670000000003',
 'LAUCN010690000000003',
 'LAUCN010710000000003',
 'LAUCN010730000000003',
 'LAUCN010750000000003',
 'LAUCN010770000000003',
 'LAUCN010790000000003',
 'LAUCN010810000000003',
 'LAUCN010830000000003',
 'LAUCN010850000000003',
 'LAUCN010870000000003',
 'LAUCN010890000000003',
 'LAUCN010910000000003',
 'LAUCN010930000000003',
 'LAUCN010950000000003',
 'LAUCN010970000000003',
 'LAUCN010990000000003',
 'LAUCN011010000000003',
 'LAUCN011030000000003',
 'LAUCN011050000000003',
 'LAUCN011070000000003',
 'LAUCN011090000000003',
 'LAUCN011110000000003',
 'LAUCN011130000000003',
 'LAUCN011150000000003',
 'LAUCN011170000000003',
 'LAUCN011190000000003',
 'LAUCN011210000000003',
 'LAUCN011230000000003',
 'LAUCN011250000000003',
 'LAUCN011270000000003',
 'LAUCN011290000000003',
 'LAUCN011310000000003',
 'LAUCN011330000000003',
 'LAUCN020130000000003',
 'LAUCN020160000000003',
 'LAUCN020200000000003',
 'LAUCN020500000000003',
 'LAUCN020600000000003',
 'LAUCN020680000000003',
 'LAUCN020700000000003',
 'LAUCN020900000000003',
 'LAUCN021000000000003',
 'LAUCN021050000000003',
 'LAUCN021100000000003',
 'LAUCN021220000000003',
 'LAUCN021300000000003',
 'LAUCN021500000000003',
 'LAUCN021580000000003',
 'LAUCN021640000000003',
 'LAUCN021700000000003',
 'LAUCN021800000000003',
 'LAUCN021850000000003',
 'LAUCN021880000000003',
 'LAUCN021950000000003',
 'LAUCN021980000000003',
 'LAUCN022200000000003',
 'LAUCN022300000000003',
 'LAUCN022400000000003',
 'LAUCN022610000000003',
 'LAUCN022750000000003',
 'LAUCN022820000000003',
 'LAUCN022900000000003',
 'LAUCN040010000000003',
 'LAUCN040030000000003',
 'LAUCN040050000000003',
 'LAUCN040070000000003',
 'LAUCN040090000000003',
 'LAUCN040110000000003',
 'LAUCN040120000000003',
 'LAUCN040130000000003',
 'LAUCN040150000000003',
 'LAUCN040170000000003',
 'LAUCN040190000000003',
 'LAUCN040210000000003',
 'LAUCN040230000000003',
 'LAUCN040250000000003',
 'LAUCN040270000000003',
 'LAUCN050010000000003',
 'LAUCN050030000000003',
 'LAUCN050050000000003',
 'LAUCN050070000000003',
 'LAUCN050090000000003',
 'LAUCN050110000000003',
 'LAUCN050130000000003',
 'LAUCN050150000000003',
 'LAUCN050170000000003',
 'LAUCN050190000000003',
 'LAUCN050210000000003',
 'LAUCN050230000000003',
 'LAUCN050250000000003',
 'LAUCN050270000000003',
 'LAUCN050290000000003',
 'LAUCN050310000000003',
 'LAUCN050330000000003',
 'LAUCN050350000000003',
 'LAUCN050370000000003',
 'LAUCN050390000000003',
 'LAUCN050410000000003',
 'LAUCN050430000000003',
 'LAUCN050450000000003',
 'LAUCN050470000000003',
 'LAUCN050490000000003',
 'LAUCN050510000000003',
 'LAUCN050530000000003',
 'LAUCN050550000000003',
 'LAUCN050570000000003',
 'LAUCN050590000000003',
 'LAUCN050610000000003',
 'LAUCN050630000000003',
 'LAUCN050650000000003',
 'LAUCN050670000000003',
 'LAUCN050690000000003',
 'LAUCN050710000000003',
 'LAUCN050730000000003',
 'LAUCN050750000000003',
 'LAUCN050770000000003',
 'LAUCN050790000000003',
 'LAUCN050810000000003',
 'LAUCN050830000000003',
 'LAUCN050850000000003',
 'LAUCN050870000000003',
 'LAUCN050890000000003',
 'LAUCN050910000000003',
 'LAUCN050930000000003',
 'LAUCN050950000000003',
 'LAUCN050970000000003',
 'LAUCN050990000000003',
 'LAUCN051010000000003',
 'LAUCN051030000000003',
 'LAUCN051050000000003',
 'LAUCN051070000000003',
 'LAUCN051090000000003',
 'LAUCN051110000000003',
 'LAUCN051130000000003',
 'LAUCN051150000000003',
 'LAUCN051170000000003',
 'LAUCN051190000000003',
 'LAUCN051210000000003',
 'LAUCN051230000000003',
 'LAUCN051250000000003',
 'LAUCN051270000000003',
 'LAUCN051290000000003',
 'LAUCN051310000000003',
 'LAUCN051330000000003',
 'LAUCN051350000000003',
 'LAUCN051370000000003',
 'LAUCN051390000000003',
 'LAUCN051410000000003',
 'LAUCN051430000000003',
 'LAUCN051450000000003',
 'LAUCN051470000000003',
 'LAUCN051490000000003',
 'LAUCN060010000000003',
 'LAUCN060030000000003',
 'LAUCN060050000000003',
 'LAUCN060070000000003',
 'LAUCN060090000000003',
 'LAUCN060110000000003',
 'LAUCN060130000000003',
 'LAUCN060150000000003',
 'LAUCN060170000000003',
 'LAUCN060190000000003',
 'LAUCN060210000000003',
 'LAUCN060230000000003',
 'LAUCN060250000000003',
 'LAUCN060270000000003',
 'LAUCN060290000000003',
 'LAUCN060310000000003',
 'LAUCN060330000000003',
 'LAUCN060350000000003',
 'LAUCN060370000000003',
 'LAUCN060390000000003',
 'LAUCN060410000000003',
 'LAUCN060430000000003',
 'LAUCN060450000000003',
 'LAUCN060470000000003',
 'LAUCN060490000000003',
 'LAUCN060510000000003',
 'LAUCN060530000000003',
 'LAUCN060550000000003',
 'LAUCN060570000000003',
 'LAUCN060590000000003',
 'LAUCN060610000000003',
 'LAUCN060630000000003',
 'LAUCN060650000000003',
 'LAUCN060670000000003',
 'LAUCN060690000000003',
 'LAUCN060710000000003',
 'LAUCN060730000000003',
 'LAUCN060750000000003',
 'LAUCN060770000000003',
 'LAUCN060790000000003',
 'LAUCN060810000000003',
 'LAUCN060830000000003',
 'LAUCN060850000000003',
 'LAUCN060870000000003',
 'LAUCN060890000000003',
 'LAUCN060910000000003',
 'LAUCN060930000000003',
 'LAUCN060950000000003',
 'LAUCN060970000000003',
 'LAUCN060990000000003',
 'LAUCN061010000000003',
 'LAUCN061030000000003',
 'LAUCN061050000000003',
 'LAUCN061070000000003',
 'LAUCN061090000000003',
 'LAUCN061110000000003',
 'LAUCN061130000000003',
 'LAUCN061150000000003',
 'LAUCN080010000000003',
 'LAUCN080030000000003',
 'LAUCN080050000000003',
 'LAUCN080070000000003',
 'LAUCN080090000000003',
 'LAUCN080110000000003',
 'LAUCN080130000000003',
 'LAUCN080140000000003',
 'LAUCN080150000000003',
 'LAUCN080170000000003',
 'LAUCN080190000000003',
 'LAUCN080210000000003',
 'LAUCN080230000000003',
 'LAUCN080250000000003',
 'LAUCN080270000000003',
 'LAUCN080290000000003',
 'LAUCN080310000000003',
 'LAUCN080330000000003',
 'LAUCN080350000000003',
 'LAUCN080370000000003',
 'LAUCN080390000000003',
 'LAUCN080410000000003',
 'LAUCN080430000000003',
 'LAUCN080450000000003',
 'LAUCN080470000000003',
 'LAUCN080490000000003',
 'LAUCN080510000000003',
 'LAUCN080530000000003',
 'LAUCN080550000000003',
 'LAUCN080570000000003',
 'LAUCN080590000000003',
 'LAUCN080610000000003',
 'LAUCN080630000000003',
 'LAUCN080650000000003',
 'LAUCN080670000000003',
 'LAUCN080690000000003',
 'LAUCN080710000000003',
 'LAUCN080730000000003',
 'LAUCN080750000000003',
 'LAUCN080770000000003',
 'LAUCN080790000000003',
 'LAUCN080810000000003',
 'LAUCN080830000000003',
 'LAUCN080850000000003',
 'LAUCN080870000000003',
 'LAUCN080890000000003',
 'LAUCN080910000000003',
 'LAUCN080930000000003',
 'LAUCN080950000000003',
 'LAUCN080970000000003',
 'LAUCN080990000000003',
 'LAUCN081010000000003',
 'LAUCN081030000000003',
 'LAUCN081050000000003',
 'LAUCN081070000000003',
 'LAUCN081090000000003',
 'LAUCN081110000000003',
 'LAUCN081130000000003',
 'LAUCN081150000000003',
 'LAUCN081170000000003',
 'LAUCN081190000000003',
 'LAUCN081210000000003',
 'LAUCN081230000000003',
 'LAUCN081250000000003',
 'LAUCN090010000000003',
 'LAUCN090030000000003',
 'LAUCN090050000000003',
 'LAUCN090070000000003',
 'LAUCN090090000000003',
 'LAUCN090110000000003',
 'LAUCN090130000000003',
 'LAUCN090150000000003',
 'LAUCN100010000000003',
 'LAUCN100030000000003',
 'LAUCN100050000000003',
 'LAUCN110010000000003',
 'LAUCN120010000000003',
 'LAUCN120030000000003',
 'LAUCN120050000000003',
 'LAUCN120070000000003',
 'LAUCN120090000000003',
 'LAUCN120110000000003',
 'LAUCN120130000000003',
 'LAUCN120150000000003',
 'LAUCN120170000000003',
 'LAUCN120190000000003',
 'LAUCN120210000000003',
 'LAUCN120230000000003',
 'LAUCN120270000000003',
 'LAUCN120290000000003',
 'LAUCN120310000000003',
 'LAUCN120330000000003',
 'LAUCN120350000000003',
 'LAUCN120370000000003',
 'LAUCN120390000000003',
 'LAUCN120410000000003',
 'LAUCN120430000000003',
 'LAUCN120450000000003',
 'LAUCN120470000000003',
 'LAUCN120490000000003',
 'LAUCN120510000000003',
 'LAUCN120530000000003',
 'LAUCN120550000000003',
 'LAUCN120570000000003',
 'LAUCN120590000000003',
 'LAUCN120610000000003',
 'LAUCN120630000000003',
 'LAUCN120650000000003',
 'LAUCN120670000000003',
 'LAUCN120690000000003',
 'LAUCN120710000000003',
 'LAUCN120730000000003',
 'LAUCN120750000000003',
 'LAUCN120770000000003',
 'LAUCN120790000000003',
 'LAUCN120810000000003',
 'LAUCN120830000000003',
 'LAUCN120850000000003',
 'LAUCN120860000000003',
 'LAUCN120870000000003',
 'LAUCN120890000000003',
 'LAUCN120910000000003',
 'LAUCN120930000000003',
 'LAUCN120950000000003',
 'LAUCN120970000000003',
 'LAUCN120990000000003',
 'LAUCN121010000000003',
 'LAUCN121030000000003',
 'LAUCN121050000000003',
 'LAUCN121070000000003',
 'LAUCN121090000000003',
 'LAUCN121110000000003',
 'LAUCN121130000000003',
 'LAUCN121150000000003',
 'LAUCN121170000000003',
 'LAUCN121190000000003',
 'LAUCN121210000000003',
 'LAUCN121230000000003',
 'LAUCN121250000000003',
 'LAUCN121270000000003',
 'LAUCN121290000000003',
 'LAUCN121310000000003',
 'LAUCN121330000000003',
 'LAUCN130010000000003',
 'LAUCN130030000000003',
 'LAUCN130050000000003',
 'LAUCN130070000000003',
 'LAUCN130090000000003',
 'LAUCN130110000000003',
 'LAUCN130130000000003',
 'LAUCN130150000000003',
 'LAUCN130170000000003',
 'LAUCN130190000000003',
 'LAUCN130210000000003',
 'LAUCN130230000000003',
 'LAUCN130250000000003',
 'LAUCN130270000000003',
 'LAUCN130290000000003',
 'LAUCN130310000000003',
 'LAUCN130330000000003',
 'LAUCN130350000000003',
 'LAUCN130370000000003',
 'LAUCN130390000000003',
 'LAUCN130430000000003',
 'LAUCN130450000000003',
 'LAUCN130470000000003',
 'LAUCN130490000000003',
 'LAUCN130510000000003',
 'LAUCN130530000000003',
 'LAUCN130550000000003',
 'LAUCN130570000000003',
 'LAUCN130590000000003',
 'LAUCN130610000000003',
 'LAUCN130630000000003',
 'LAUCN130650000000003',
 'LAUCN130670000000003',
 'LAUCN130690000000003',
 'LAUCN130710000000003',
 'LAUCN130730000000003',
 'LAUCN130750000000003',
 'LAUCN130770000000003',
 'LAUCN130790000000003',
 'LAUCN130810000000003',
 'LAUCN130830000000003',
 'LAUCN130850000000003',
 'LAUCN130870000000003',
 'LAUCN130890000000003',
 'LAUCN130910000000003',
 'LAUCN130930000000003',
 'LAUCN130950000000003',
 'LAUCN130970000000003',
 'LAUCN130990000000003',
 'LAUCN131010000000003',
 'LAUCN131030000000003',
 'LAUCN131050000000003',
 'LAUCN131070000000003',
 'LAUCN131090000000003',
 'LAUCN131110000000003',
 'LAUCN131130000000003',
 'LAUCN131150000000003',
 'LAUCN131170000000003',
 'LAUCN131190000000003',
 'LAUCN131210000000003',
 'LAUCN131230000000003',
 'LAUCN131250000000003',
 'LAUCN131270000000003',
 'LAUCN131290000000003',
 'LAUCN131310000000003',
 'LAUCN131330000000003',
 'LAUCN131350000000003',
 'LAUCN131370000000003',
 'LAUCN131390000000003',
 'LAUCN131410000000003',
 'LAUCN131430000000003',
 'LAUCN131450000000003',
 'LAUCN131470000000003',
 'LAUCN131490000000003',
 'LAUCN131510000000003',
 'LAUCN131530000000003',
 'LAUCN131550000000003',
 'LAUCN131570000000003',
 'LAUCN131590000000003',
 'LAUCN131610000000003',
 'LAUCN131630000000003',
 'LAUCN131650000000003',
 'LAUCN131670000000003',
 'LAUCN131690000000003',
 'LAUCN131710000000003',
 'LAUCN131730000000003',
 'LAUCN131750000000003',
 'LAUCN131770000000003',
 'LAUCN131790000000003',
 'LAUCN131810000000003',
 'LAUCN131830000000003',
 'LAUCN131850000000003',
 'LAUCN131870000000003',
 'LAUCN131890000000003',
 'LAUCN131910000000003',
 'LAUCN131930000000003',
 'LAUCN131950000000003',
 'LAUCN131970000000003',
 'LAUCN131990000000003',
 'LAUCN132010000000003',
 'LAUCN132050000000003',
 'LAUCN132070000000003',
 'LAUCN132090000000003',
 'LAUCN132110000000003',
 'LAUCN132130000000003',
 'LAUCN132150000000003',
 'LAUCN132170000000003',
 'LAUCN132190000000003',
 'LAUCN132210000000003',
 'LAUCN132230000000003',
 'LAUCN132250000000003',
 'LAUCN132270000000003',
 'LAUCN132290000000003',
 'LAUCN132310000000003',
 'LAUCN132330000000003',
 'LAUCN132350000000003',
 'LAUCN132370000000003',
 'LAUCN132390000000003',
 'LAUCN132410000000003',
 'LAUCN132430000000003',
 'LAUCN132450000000003',
 'LAUCN132470000000003',
 'LAUCN132490000000003',
 'LAUCN132510000000003',
 'LAUCN132530000000003',
 'LAUCN132550000000003',
 'LAUCN132570000000003',
 'LAUCN132590000000003',
 'LAUCN132610000000003',
 'LAUCN132630000000003',
 'LAUCN132650000000003',
 'LAUCN132670000000003',
 'LAUCN132690000000003',
 'LAUCN132710000000003',
 'LAUCN132730000000003',
 'LAUCN132750000000003',
 'LAUCN132770000000003',
 'LAUCN132790000000003',
 'LAUCN132810000000003',
 'LAUCN132830000000003',
 'LAUCN132850000000003',
 'LAUCN132870000000003',
 'LAUCN132890000000003',
 'LAUCN132910000000003',
 'LAUCN132930000000003',
 'LAUCN132950000000003',
 'LAUCN132970000000003',
 'LAUCN132990000000003',
 'LAUCN133010000000003',
 'LAUCN133030000000003',
 'LAUCN133050000000003',
 'LAUCN133070000000003',
 'LAUCN133090000000003',
 'LAUCN133110000000003',
 'LAUCN133130000000003',
 'LAUCN133150000000003',
 'LAUCN133170000000003',
 'LAUCN133190000000003',
 'LAUCN133210000000003',
 'LAUCN150010000000003',
 'LAUCN150030000000003',
 'LAUCN150050000000003',
 'LAUCN150070000000003',
 'LAUCN150090000000003',
 'LAUCN160010000000003',
 'LAUCN160030000000003',
 'LAUCN160050000000003',
 'LAUCN160070000000003',
 'LAUCN160090000000003',
 'LAUCN160110000000003',
 'LAUCN160130000000003',
 'LAUCN160150000000003',
 'LAUCN160170000000003',
 'LAUCN160190000000003',
 'LAUCN160210000000003',
 'LAUCN160230000000003',
 'LAUCN160250000000003',
 'LAUCN160270000000003',
 'LAUCN160290000000003',
 'LAUCN160310000000003',
 'LAUCN160330000000003',
 'LAUCN160350000000003',
 'LAUCN160370000000003',
 'LAUCN160390000000003',
 'LAUCN160410000000003',
 'LAUCN160430000000003',
 'LAUCN160450000000003',
 'LAUCN160470000000003',
 'LAUCN160490000000003',
 'LAUCN160510000000003',
 'LAUCN160530000000003',
 'LAUCN160550000000003',
 'LAUCN160570000000003',
 'LAUCN160590000000003',
 'LAUCN160610000000003',
 'LAUCN160630000000003',
 'LAUCN160650000000003',
 'LAUCN160670000000003',
 'LAUCN160690000000003',
 'LAUCN160710000000003',
 'LAUCN160730000000003',
 'LAUCN160750000000003',
 'LAUCN160770000000003',
 'LAUCN160790000000003',
 'LAUCN160810000000003',
 'LAUCN160830000000003',
 'LAUCN160850000000003',
 'LAUCN160870000000003',
 'LAUCN170010000000003',
 'LAUCN170030000000003',
 'LAUCN170050000000003',
 'LAUCN170070000000003',
 'LAUCN170090000000003',
 'LAUCN170110000000003',
 'LAUCN170130000000003',
 'LAUCN170150000000003',
 'LAUCN170170000000003',
 'LAUCN170190000000003',
 'LAUCN170210000000003',
 'LAUCN170230000000003',
 'LAUCN170250000000003',
 'LAUCN170270000000003',
 'LAUCN170290000000003',
 'LAUCN170310000000003',
 'LAUCN170330000000003',
 'LAUCN170350000000003',
 'LAUCN170370000000003',
 'LAUCN170390000000003',
 'LAUCN170410000000003',
 'LAUCN170430000000003',
 'LAUCN170450000000003',
 'LAUCN170470000000003',
 'LAUCN170490000000003',
 'LAUCN170510000000003',
 'LAUCN170530000000003',
 'LAUCN170550000000003',
 'LAUCN170570000000003',
 'LAUCN170590000000003',
 'LAUCN170610000000003',
 'LAUCN170630000000003',
 'LAUCN170650000000003',
 'LAUCN170670000000003',
 'LAUCN170690000000003',
 'LAUCN170710000000003',
 'LAUCN170730000000003',
 'LAUCN170750000000003',
 'LAUCN170770000000003',
 'LAUCN170790000000003',
 'LAUCN170810000000003',
 'LAUCN170830000000003',
 'LAUCN170850000000003',
 'LAUCN170870000000003',
 'LAUCN170890000000003',
 'LAUCN170910000000003',
 'LAUCN170930000000003',
 'LAUCN170950000000003',
 'LAUCN170970000000003',
 'LAUCN170990000000003',
 'LAUCN171010000000003',
 'LAUCN171030000000003',
 'LAUCN171050000000003',
 'LAUCN171070000000003',
 'LAUCN171090000000003',
 'LAUCN171110000000003',
 'LAUCN171130000000003',
 'LAUCN171150000000003',
 'LAUCN171170000000003',
 'LAUCN171190000000003',
 'LAUCN171210000000003',
 'LAUCN171230000000003',
 'LAUCN171250000000003',
 'LAUCN171270000000003',
 'LAUCN171290000000003',
 'LAUCN171310000000003',
 'LAUCN171330000000003',
 'LAUCN171350000000003',
 'LAUCN171370000000003',
 'LAUCN171390000000003',
 'LAUCN171410000000003',
 'LAUCN171430000000003',
 'LAUCN171450000000003',
 'LAUCN171470000000003',
 'LAUCN171490000000003',
 'LAUCN171510000000003',
 'LAUCN171530000000003',
 'LAUCN171550000000003',
 'LAUCN171570000000003',
 'LAUCN171590000000003',
 'LAUCN171610000000003',
 'LAUCN171630000000003',
 'LAUCN171650000000003',
 'LAUCN171670000000003',
 'LAUCN171690000000003',
 'LAUCN171710000000003',
 'LAUCN171730000000003',
 'LAUCN171750000000003',
 'LAUCN171770000000003',
 'LAUCN171790000000003',
 'LAUCN171810000000003',
 'LAUCN171830000000003',
 'LAUCN171850000000003',
 'LAUCN171870000000003',
 'LAUCN171890000000003',
 'LAUCN171910000000003',
 'LAUCN171930000000003',
 'LAUCN171950000000003',
 'LAUCN171970000000003',
 'LAUCN171990000000003',
 'LAUCN172010000000003',
 'LAUCN172030000000003',
 'LAUCN180010000000003',
 'LAUCN180030000000003',
 'LAUCN180050000000003',
 'LAUCN180070000000003',
 'LAUCN180090000000003',
 'LAUCN180110000000003',
 'LAUCN180130000000003',
 'LAUCN180150000000003',
 'LAUCN180170000000003',
 'LAUCN180190000000003',
 'LAUCN180210000000003',
 'LAUCN180230000000003',
 'LAUCN180250000000003',
 'LAUCN180270000000003',
 'LAUCN180290000000003',
 'LAUCN180310000000003',
 'LAUCN180330000000003',
 'LAUCN180350000000003',
 'LAUCN180370000000003',
 'LAUCN180390000000003',
 'LAUCN180410000000003',
 'LAUCN180430000000003',
 'LAUCN180450000000003',
 'LAUCN180470000000003',
 'LAUCN180490000000003',
 'LAUCN180510000000003',
 'LAUCN180530000000003',
 'LAUCN180550000000003',
 'LAUCN180570000000003',
 'LAUCN180590000000003',
 'LAUCN180610000000003',
 'LAUCN180630000000003',
 'LAUCN180650000000003',
 'LAUCN180670000000003',
 'LAUCN180690000000003',
 'LAUCN180710000000003',
 'LAUCN180730000000003',
 'LAUCN180750000000003',
 'LAUCN180770000000003',
 'LAUCN180790000000003',
 'LAUCN180810000000003',
 'LAUCN180830000000003',
 'LAUCN180850000000003',
 'LAUCN180870000000003',
 'LAUCN180890000000003',
 'LAUCN180910000000003',
 'LAUCN180930000000003',
 'LAUCN180950000000003',
 'LAUCN180970000000003',
 'LAUCN180990000000003',
 'LAUCN181010000000003',
 'LAUCN181030000000003',
 'LAUCN181050000000003',
 'LAUCN181070000000003',
 'LAUCN181090000000003',
 'LAUCN181110000000003',
 'LAUCN181130000000003',
 'LAUCN181150000000003',
 'LAUCN181170000000003',
 'LAUCN181190000000003',
 'LAUCN181210000000003',
 'LAUCN181230000000003',
 'LAUCN181250000000003',
 'LAUCN181270000000003',
 'LAUCN181290000000003',
 'LAUCN181310000000003',
 'LAUCN181330000000003',
 'LAUCN181350000000003',
 'LAUCN181370000000003',
 'LAUCN181390000000003',
 'LAUCN181410000000003',
 'LAUCN181430000000003',
 'LAUCN181450000000003',
 'LAUCN181470000000003',
 'LAUCN181490000000003',
 'LAUCN181510000000003',
 'LAUCN181530000000003',
 'LAUCN181550000000003',
 'LAUCN181570000000003',
 'LAUCN181590000000003',
 'LAUCN181610000000003',
 'LAUCN181630000000003',
 'LAUCN181650000000003',
 'LAUCN181670000000003',
 'LAUCN181690000000003',
 'LAUCN181710000000003',
 'LAUCN181730000000003',
 'LAUCN181750000000003',
 'LAUCN181770000000003',
 'LAUCN181790000000003',
 'LAUCN181810000000003',
 'LAUCN181830000000003',
 'LAUCN190010000000003',
 'LAUCN190030000000003',
 'LAUCN190050000000003',
 'LAUCN190070000000003',
 'LAUCN190090000000003',
 'LAUCN190110000000003',
 'LAUCN190130000000003',
 'LAUCN190150000000003',
 'LAUCN190170000000003',
 'LAUCN190190000000003',
 'LAUCN190210000000003',

In [5]:
# # Split series_ids into chunks of 50 because currently only  50 series per query are allowed
# # More info here: https://www.bls.gov/developers/api_faqs.htm#register2

# chunks = [series_ids[i:i + 50] for i in range(1, len(series_ids))]

# chunks

len(series_ids)

3142

In [6]:
chunks = [series_ids[i:i + 50] for i in range(0, len(series_ids)+1, 50)]

In [7]:
len(chunks)

63

In [11]:
api_key = '5076bf053e804fcb965cb07c041786ad'

In [12]:

url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'
api_key = '5076bf053e804fcb965cb07c041786ad'
path = '..\\'

headers = {'Content-Type': 'application/json'}

for chunk in chunks:
    data = {
        "seriesid": chunk,
        "startyear": "2018",
        "endyear": "2023",
        "registrationkey": api_key
    }
    data_json = json.dumps(data)
    
    url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'
    response = requests.post(url, data=data_json, headers=headers)
    
    json_data = json.loads(response.text)
    
    for series in json_data['Results']['series']:
        x = prettytable.PrettyTable(["series id", "year", "period", "value", "footnotes"])
        series_id = series['seriesID']
        
        for item in series['data']:
            year = item['year']
            period = item['period']
            value = item['value']
            footnotes = ",".join(footnote['text'] for footnote in item['footnotes'] if footnote)
            
            if 'M01' <= period <= 'M12':
                x.add_row([series_id, year, period, value, footnotes])
        
        output_path = f"{path}data\\2_intermediate\\unemp_bls\\{series_id}.txt"
        with open(output_path, 'w') as output:
            output.write(x.get_string())
    
    time.sleep(12)  # This line is indented to be inside the outer loop

In [13]:
# specify your path
path = '..\\data\\2_intermediate\\unemp_bls\\'

# find all .txt files in the path
all_files = glob.glob(path + "/*.txt")

# create an empty list to store dataframes
li = []

In [14]:
# loop through the list of .txt files
for filename in all_files:
    # open the file
    with open(filename, 'r') as f:
        # read the lines into a list, ignoring lines starting with '+'
        lines = [line for line in f if not line.startswith('+')]
    # join the lines back into a single string, then use StringIO to read it into a DataFrame
    df = pd.read_csv(io.StringIO(''.join(lines)), sep='|', skipfooter=1, engine='python')
    li.append(df)

In [15]:
# concatenate all dataframes in the list
df = pd.concat(li, ignore_index=True)

In [16]:
df

,Unnamed: 0,series id,year,period,value,footnotes,Unnamed: 6,series id
0,NaN,LAUCN010010000000003,2023,M12,2.2,,NaN,NaN
1,NaN,LAUCN010010000000003,2023,M11,2.2,,NaN,NaN
2,NaN,LAUCN010010000000003,2023,M10,2.3,,NaN,NaN
3,NaN,LAUCN010010000000003,2023,M09,2.3,,NaN,NaN
4,NaN,LAUCN010010000000003,2023,M08,2.5,,NaN,NaN
...,...,...,...,...,...,...,...,...
222958,NaN,LAUCN560450000000003,2018,M06,3.9,,NaN,NaN
222959,NaN,LAUCN560450000000003,2018,M05,3.3,,NaN,NaN
222960,NaN,LAUCN560450000000003,2018,M04,3.8,,NaN,NaN
222961,NaN,LAUCN560450000000003,2018,M03,4.2,,NaN,NaN
222962,NaN,LAUCN560450000000003,2018,M02,4.2,,NaN,NaN

In [17]:
len(df)

222963

In [18]:
len(df.columns)

8

In [19]:
df_subset = df.iloc[:, 1:6]

In [20]:
df_subset

              series id         year    period    value    footnotes
0        LAUCN010010000000003    2023    M12         2.2
1        LAUCN010010000000003    2023    M11         2.2
2        LAUCN010010000000003    2023    M10         2.3
3        LAUCN010010000000003    2023    M09         2.3
4        LAUCN010010000000003    2023    M08         2.5
...                        ...    ...       ...      ...          ...
222958   LAUCN560450000000003    2018    M06         3.9
222959   LAUCN560450000000003    2018    M05         3.3
222960   LAUCN560450000000003    2018    M04         3.8
222961   LAUCN560450000000003    2018    M03         4.2
222962   LAUCN560450000000003    2018    M02         4.2

[222963 rows x 5 columns]

In [21]:
df_subset.columns = ['seriesid', 'Year', 'period', 'lau_unemprate', 'footnotes']

In [22]:
df_subset

                      seriesid  Year    period  lau_unemprate    footnotes
0        LAUCN010010000000003   2023    M12               2.2
1        LAUCN010010000000003   2023    M11               2.2
2        LAUCN010010000000003   2023    M10               2.3
3        LAUCN010010000000003   2023    M09               2.3
4        LAUCN010010000000003   2023    M08               2.5
...                        ...   ...       ...            ...          ...
222958   LAUCN560450000000003   2018    M06               3.9
222959   LAUCN560450000000003   2018    M05               3.3
222960   LAUCN560450000000003   2018    M04               3.8
222961   LAUCN560450000000003   2018    M03               4.2
222962   LAUCN560450000000003   2018    M02               4.2

[222963 rows x 5 columns]

In [23]:
df_subset['geofips'] = df_subset['seriesid'].str.slice(6, 11)
df_subset['Month'] = df_subset['period'].str.slice(3, 5)

In [24]:
df_subset

,seriesid,Year,period,lau_unemprate,footnotes,geofips,Month
0,LAUCN010010000000003,2023,M12,2.2,,01001,12
1,LAUCN010010000000003,2023,M11,2.2,,01001,11
2,LAUCN010010000000003,2023,M10,2.3,,01001,10
3,LAUCN010010000000003,2023,M09,2.3,,01001,09
4,LAUCN010010000000003,2023,M08,2.5,,01001,08
...,...,...,...,...,...,...,...
222958,LAUCN560450000000003,2018,M06,3.9,,56045,06
222959,LAUCN560450000000003,2018,M05,3.3,,56045,05
222960,LAUCN560450000000003,2018,M04,3.8,,56045,04
222961,LAUCN560450000000003,2018,M03,4.2,,56045,03
222962,LAUCN560450000000003,2018,M02,4.2,,56045,02

In [25]:
print(df_subset['geofips'].dtypes)

object

In [26]:
df_subset.dtypes

seriesid          object
Year              object
period            object
lau_unemprate    float64
footnotes         object
geofips           object
Month             object
dtype: object

In [27]:
df_subset['seriesid'] = df_subset['seriesid'].astype(str)
df_subset['Year'] = df_subset['Year'].astype(str)
df_subset['period'] = df_subset['period'].astype(str)
df_subset['footnotes'] = df_subset['footnotes'].astype(str)
df_subset['geofips'] = df_subset['geofips'].astype(str)
df_subset['Month'] = df_subset['Month'].astype(str)

In [28]:
df_subset.dtypes

seriesid          object
Year              object
period            object
lau_unemprate    float64
footnotes         object
geofips           object
Month             object
dtype: object

In [29]:
df_subset['YearMonth'] = df_subset['Year'] + df_subset['Month']

In [30]:
df_subset

,seriesid,Year,period,lau_unemprate,footnotes,geofips,Month,YearMonth
0,LAUCN010010000000003,2023,M12,2.2,,01001,12,202312
1,LAUCN010010000000003,2023,M11,2.2,,01001,11,202311
2,LAUCN010010000000003,2023,M10,2.3,,01001,10,202310
3,LAUCN010010000000003,2023,M09,2.3,,01001,09,202309
4,LAUCN010010000000003,2023,M08,2.5,,01001,08,202308
...,...,...,...,...,...,...,...,...
222958,LAUCN560450000000003,2018,M06,3.9,,56045,06,201806
222959,LAUCN560450000000003,2018,M05,3.3,,56045,05,201805
222960,LAUCN560450000000003,2018,M04,3.8,,56045,04,201804
222961,LAUCN560450000000003,2018,M03,4.2,,56045,03,201803
222962,LAUCN560450000000003,2018,M02,4.2,,56045,02,201802

In [54]:
df_subset.to_stata(path + 'county_monthly_unemp.dta')