In [1]:
#setup
import pandas as pd
import numpy as np
import os

In [2]:
url='https://raw.githubusercontent.com/OxCGRT/covid-policy-dataset/main/data/OxCGRT_compact_subnational_v1.csv'
df=pd.read_csv(url)
path="C:/Users/rivera30/OneDrive - NYU Langone Health/EvictionMoratoria_OD/"

C:\Users\rivera30\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3526: DtypeWarning: Columns (4,5,53) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
df

,CountryName,CountryCode,RegionName,RegionCode,CityName,CityCode,Jurisdiction,Date,C1M_School.closing,C1M_Flag,...,V3_Vaccine.Financial.Support..summary.,V4_Mandatory.Vaccination..summary.,ConfirmedCases,ConfirmedDeaths,MajorityVaccinated,PopulationVaccinated,StringencyIndex_Average,GovernmentResponseIndex_Average,ContainmentHealthIndex_Average,EconomicSupportIndex
0,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200101,0,NaN,...,0,NaN,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
1,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200102,0,NaN,...,0,NaN,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
2,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200103,0,NaN,...,0,NaN,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
3,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200104,0,NaN,...,0,NaN,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
4,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200105,0,NaN,...,0,NaN,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239656,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221227,0,NaN,...,5,0.0,182847.0,1958.0,V,52.9,23.37,30.85,35.26,0.0
239657,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221228,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0
239658,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221229,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0
239659,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221230,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0
239660,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221231,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0

In [4]:
usdf = df[df["CountryName"] == 'United States']

In [5]:
usdf

,CountryName,CountryCode,RegionName,RegionCode,CityName,CityCode,Jurisdiction,Date,C1M_School.closing,C1M_Flag,...,V3_Vaccine.Financial.Support..summary.,V4_Mandatory.Vaccination..summary.,ConfirmedCases,ConfirmedDeaths,MajorityVaccinated,PopulationVaccinated,StringencyIndex_Average,GovernmentResponseIndex_Average,ContainmentHealthIndex_Average,EconomicSupportIndex
182669,United States,USA,NaN,NaN,NaN,NaN,NAT_TOTAL,20200101,0,NaN,...,0,0.0,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
182670,United States,USA,NaN,NaN,NaN,NaN,NAT_TOTAL,20200102,0,NaN,...,0,0.0,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
182671,United States,USA,NaN,NaN,NaN,NaN,NAT_TOTAL,20200103,0,NaN,...,0,0.0,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
182672,United States,USA,NaN,NaN,NaN,NaN,NAT_TOTAL,20200104,0,NaN,...,0,0.0,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
182673,United States,USA,NaN,NaN,NaN,NaN,NAT_TOTAL,20200105,0,NaN,...,0,0.0,0.0,0.0,NV,0,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239656,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221227,0,NaN,...,5,0.0,182847.0,1958.0,V,52.9,23.37,30.85,35.26,0.0
239657,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221228,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0
239658,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221229,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0
239659,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221230,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0
239660,United States,USA,Wyoming,US_WY,NaN,NaN,STATE_TOTAL,20221231,0,NaN,...,5,0.0,182847.0,1958.0,V,52.92,23.37,30.85,35.26,0.0

In [6]:
counts = usdf["RegionName"].value_counts()

In [7]:
counts

Alaska            1096
Pennsylvania      1096
North Dakota      1096
Nebraska          1096
New Hampshire     1096
New Jersey        1096
New Mexico        1096
Nevada            1096
New York          1096
Ohio              1096
Oklahoma          1096
Oregon            1096
Rhode Island      1096
Montana           1096
South Carolina    1096
South Dakota      1096
Tennessee         1096
Texas             1096
Utah              1096
Virginia          1096
Vermont           1096
Washington        1096
Wisconsin         1096
West Virginia     1096
North Carolina    1096
Mississippi       1096
Alabama           1096
Iowa              1096
Arkansas          1096
Arizona           1096
California        1096
Colorado          1096
Connecticut       1096
Washington DC     1096
Delaware          1096
Florida           1096
Georgia           1096
Hawaii            1096
Idaho             1096
Missouri          1096
Illinois          1096
Indiana           1096
Kansas            1096
Kentucky          1096
Louisiana         1096
Massachusetts     1096
Maryland          1096
Maine             1096
Michigan          1096
Minnesota         1096
Wyoming           1096
Name: RegionName, dtype: int64

In [17]:
usdf2 = usdf.dropna(subset=["RegionName"], how='any')

In [18]:
usdf2["Date"].value_counts()

20200101    51
20211229    51
20220104    51
20220103    51
20220102    51
            ..
20210106    51
20210107    51
20210108    51
20210109    51
20221231    51
Name: Date, Length: 1096, dtype: int64

In [19]:
usdf2["Jurisdiction"].value_counts()

STATE_TOTAL    55896
Name: Jurisdiction, dtype: int64

In [20]:
usdf2["CityName"].value_counts()

Series([], Name: CityName, dtype: int64)

In [21]:
usdf2_subset = usdf2[['RegionName', 'StringencyIndex_Average', 'GovernmentResponseIndex_Average', 
                      'ContainmentHealthIndex_Average', 'EconomicSupportIndex', 'Date']]

In [22]:
usdf2_subset.to_stata(path+"data/2_intermediate/"+"OxCGRT_US"+".dta")

In [23]:
#usdf2.to_csv(path+"data/2_intermediate/"+"OxCGRT_US"+".csv")

In [12]:
url1='https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/United%20States/OxCGRT_USA_latest.csv'
df1=pd.read_csv(url1)

In [13]:
df1

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1M_School closing,C1M_Flag,C2M_Workplace closing,C2M_Flag,...,MajorityVaccinated,PopulationVaccinated,StringencyIndex_Average,StringencyIndex_Average_ForDisplay,GovernmentResponseIndex_Average,GovernmentResponseIndex_Average_ForDisplay,ContainmentHealthIndex_Average,ContainmentHealthIndex_Average_ForDisplay,EconomicSupportIndex,EconomicSupportIndex_ForDisplay
0,United States,USA,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,United States,USA,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2,United States,USA,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
3,United States,USA,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
4,United States,USA,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56987,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221227,0.0,NaN,0.0,NaN,...,V,52.90,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56988,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221228,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56989,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221229,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56990,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221230,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56991,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221231,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0

In [14]:
us_df1 = df1[df1["CountryName"] == 'United States']

In [15]:
us_df1

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1M_School closing,C1M_Flag,C2M_Workplace closing,C2M_Flag,...,MajorityVaccinated,PopulationVaccinated,StringencyIndex_Average,StringencyIndex_Average_ForDisplay,GovernmentResponseIndex_Average,GovernmentResponseIndex_Average_ForDisplay,ContainmentHealthIndex_Average,ContainmentHealthIndex_Average_ForDisplay,EconomicSupportIndex,EconomicSupportIndex_ForDisplay
0,United States,USA,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,United States,USA,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2,United States,USA,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
3,United States,USA,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
4,United States,USA,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,0.0,NaN,...,NV,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56987,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221227,0.0,NaN,0.0,NaN,...,V,52.90,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56988,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221228,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56989,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221229,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56990,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221230,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56991,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221231,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0

In [16]:
us_df1_clean = us_df1.dropna(subset=["RegionName"], how='any')

In [17]:
us_df1_clean

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1M_School closing,C1M_Flag,C2M_Workplace closing,C2M_Flag,...,MajorityVaccinated,PopulationVaccinated,StringencyIndex_Average,StringencyIndex_Average_ForDisplay,GovernmentResponseIndex_Average,GovernmentResponseIndex_Average_ForDisplay,ContainmentHealthIndex_Average,ContainmentHealthIndex_Average_ForDisplay,EconomicSupportIndex,EconomicSupportIndex_ForDisplay
1096,United States,USA,Alaska,US_AK,STATE_TOTAL,20200101,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1097,United States,USA,Alaska,US_AK,STATE_TOTAL,20200102,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1098,United States,USA,Alaska,US_AK,STATE_TOTAL,20200103,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1099,United States,USA,Alaska,US_AK,STATE_TOTAL,20200104,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1100,United States,USA,Alaska,US_AK,STATE_TOTAL,20200105,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56987,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221227,0.0,NaN,0.0,NaN,...,V,52.90,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56988,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221228,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56989,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221229,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56990,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221230,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0
56991,United States,USA,Wyoming,US_WY,STATE_TOTAL,20221231,0.0,NaN,0.0,NaN,...,V,52.92,23.37,23.37,30.85,30.85,35.26,35.26,0.0,0.0

In [18]:
us_df1_clean["RegionName"].value_counts()

Alaska            1096
Pennsylvania      1096
North Dakota      1096
Nebraska          1096
New Hampshire     1096
New Jersey        1096
New Mexico        1096
Nevada            1096
New York          1096
Ohio              1096
Oklahoma          1096
Oregon            1096
Rhode Island      1096
Montana           1096
South Carolina    1096
South Dakota      1096
Tennessee         1096
Texas             1096
Utah              1096
Virginia          1096
Vermont           1096
Washington        1096
Wisconsin         1096
West Virginia     1096
North Carolina    1096
Mississippi       1096
Alabama           1096
Iowa              1096
Arkansas          1096
Arizona           1096
California        1096
Colorado          1096
Connecticut       1096
Washington DC     1096
Delaware          1096
Florida           1096
Georgia           1096
Hawaii            1096
Idaho             1096
Missouri          1096
Illinois          1096
Indiana           1096
Kansas            1096
Kentucky          1096
Louisiana         1096
Massachusetts     1096
Maryland          1096
Maine             1096
Michigan          1096
Minnesota         1096
Wyoming           1096
Name: RegionName, dtype: int64

In [19]:
us_df1_clean["Date"].value_counts()

20200101    51
20211229    51
20220104    51
20220103    51
20220102    51
            ..
20210106    51
20210107    51
20210108    51
20210109    51
20221231    51
Name: Date, Length: 1096, dtype: int64